### ISSUE TITLE
IOCRec代码获取问题

### ISSUE THREAD

**Issue by Dethanker** [QinHsiu/ICSRec#12]
作者您好，请问您论文对比实验中IOCRec的结果是通过作者提供的代码复现的吗？我向IOCRec的作者发送了邮件请求获取代码但是没有得到回复

**Comment by QinHsiu** [comment]
你好，我是参考了IOCRec(非官方)开源代码复现的结果，为了保证公平公正，所有基线模型输入都是一样的，如果还有关于该模型的疑问可以向原论文作者进行请教。
