### ISSUE TITLE
训练超参数

### ISSUE THREAD

**Issue by hunaghuohui** [QinHsiu/ICSRec#2]
你好，这篇工作github上面的训练超参数只有Beauty数据集的，能提供其他数据集的训练超参数吗？非常感谢！还是说每个数据集的训练超参数都一样呢。

**Comment by QinHsiu** [comment]
你好，非常感谢你对我们工作的关注，我们已经将四个数据集所使用的训练参数开源，位置在目录scripts下面，里面有四个脚本是用于训练的，参数已经提供在脚本里面。最后谢谢你对我们工作的关注。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月29日(周三) 晚上7:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [QinHsiu/ICSRec] 训练超参数 (Issue #2)




 
你好，这篇工作github上面的训练超参数只有Beauty数据集的，能提供其他数据集的训练超参数吗？非常感谢！还是说每个数据集的训练超参数都一样呢。
