### ISSUE TITLE
对比试验复现问题

### ISSUE THREAD

**Issue by syf1844803351** [QinHsiu/ICSRec#6]
您好，请问IOCRec您复现的数据集是从哪里找的呢，他的格式好像和常见的(user_id,item_id1,item_id2.......)不太一样。
您MCLRec的baseline链接挂掉了，可以补一下么，麻烦您了。

**Comment by QinHsiu** [comment]
你好，我是参考了IOCRec(非官方)开源代码复现的结果，为了保证公平公正，所有基线模型输入都是一样的，如果还有关于该模型的疑问可以向原论文作者进行请教；MCLRec的baseline链接我这边是可以正常访问的，请你刷新试一试。

**Comment by syf1844803351** [comment]
> 你好，我是参考了IOCRec(非官方)开源代码复现的结果，为了保证公平公正，所有基线模型输入都是一样的，如果还有关于该模型的疑问可以向原论文作者进行请教；MCLRec的baseline链接我这边是可以正常访问的，请你刷新试一试。

链接可以访问了，麻烦您了。
