### ISSUE TITLE
对比实验复现问题

### ISSUE THREAD

**Issue by Dethanker** [QinHsiu/ICSRec#7]
作者您好，感谢您有效的开源代码。我个人在复现您的代码的时候，在amazon的三个数据集的偏差在3%以内，在ML-1M的偏差在5%以内，这个偏差算正常吗？

**Comment by Dethanker** [comment]
我们的实验环境：a single Tesla V100 GPU

**Comment by QinHsiu** [comment]
你好，误差在3%之内是比较合理的，具体原因可以参考：https://github.com/QinHsiu/ICSRec/issues/3
