### ISSUE TITLE
About Amazon dataset 

### ISSUE THREAD

**Issue by yinliup99** [QinHsiu/ICSRec#9]
Hi, thanks a lot for your work. I'm wondering if the Amazon dataset used in this research is from 2014 or 2018?

**Comment by QinHsiu** [comment]
We use the same dataset as CoSeRec[1] and ICLRec[2] for our work, which should be from 2014. 

[1] https://github.com/salesforce/CoSeRec
[2] https://github.com/salesforce/ICLRec
